name: Agoric SDK restore Golang build
description: 'Set up Golang environment and restore cached built files'

inputs:
  go-version:
    description: 'The version of Go to use'
    required: true

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo GOPATH="$HOME/go" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v3
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-go@v4
      with:
        cache-dependency-path: golang/cosmos/go.sum
        go-version: ${{ inputs.go-version }}
    - name: go mod download
      working-directory: ./golang/cosmos
      run: go mod download
      shell: bash
